apiVersion: apps/v1
kind: Deployment
metadata:
  name: service_name
  labels:
    app: service_name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service_name
  template:
    metadata:
      labels:
        app: service_name
    spec:
      volumes:
        - name: workspace-volume
          emptyDir: {}
      initContainers:
        - name: copy-s3-resources
          image: amazon/aws-cli
          command: ["/bin/sh", "-c"]
          args:
            - aws s3 cp s3://coding-labs/labs/service_name/ /workspace/ --recursive  && echo "Resources copied from S3";
          env:
            - name: AWS_ACCESS_KEY_ID
              value: aws-key
            - name: AWS_SECRET_ACCESS_KEY
              value: aws-secret
            - name: AWS_DEFAULT_REGION
              value: aws-region
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace
      containers:
        - name: runner
          image: vivek6201/labs-runner:latest
          env:
            - name: AWS_ACCESS_KEY
              value: aws-key
            - name: AWS_SECRET_KEY
              value: aws-secret
            - name: AWS_REGION
              value: aws-region
            - name: AWS_BUCKET_NAME
              value: aws-bucket-name
          resources:
            requests:
              cpu: "0.3"
              memory: "500Mi"
            limits:
              cpu: "0.5"
              memory: "800Mi"
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace
        - name: tunnel-server
          image: vivek6201/labs-tunnel-server:latest
          ports:
            - containerPort: 8080
            - containerPort: 8000
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace
          resources:
            requests:
              cpu: "0.3"
              memory: "500Mi"
            limits:
              cpu: "0.5"
              memory: "800Mi"
      
---
apiVersion: v1
kind: Service
metadata:
  name: service_name
spec:
  selector:
    app: service_name
  ports:
    - protocol: TCP
      name: user
      port: 8000
      targetPort: 8000
    - protocol: TCP
      name: ws
      port: 4000
      targetPort: 4000
    - protocol: TCP
      name: tunnel-server
      port: 8080
      targetPort: 8080


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service_name
  labels:
    name: service_name
spec:
  ingressClassName: nginx
  rules:
    - host: service_name.labs.letscodeofficial.tech
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: service_name
                port:
                  number: 4000
    - host: service_name.lab-output.letscodeofficial.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service_name
                port:
                  number: 8000
    - host: service_name.lab-tunnel.letscodeofficial.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service_name
                port:
                  number: 8080
